[General]
# Specify the network to be simulated (general .ned file)
network = src.ServerSystem

# Simulation duration set to one year (365 days * 24 hours)
sim-time-limit = 8760h 

# The precision of the simulation clock - 'us' (microseconds)
simtime-resolution = us

# -------------------------------------------------------------------------
# PARAMETER RANGE
# -------------------------------------------------------------------------
# This syntax makes the simulation run 5 times, varying the number of 
# programmers from 1 to 5. It helps to identify the minimum staff amount
# needed to keep the  average number of failed servers below the target 
# threshold
*.repairCenter.numProgrammers = ${num=1..5}

# -------------------------------------------------------------------------
# SERVER ATTACK PARAMETERS
# -------------------------------------------------------------------------
# Mean time between attacks for each server. These values correspond to the
# exponential distribution means provided in the problem statement
*.server[0].attackMean = 14h
*.server[1].attackMean = 26h
*.server[2].attackMean = 32h
*.server[3].attackMean = 64h
*.server[4].attackMean = 70h

# -------------------------------------------------------------------------
# STATISTICS COLLECTION
# -------------------------------------------------------------------------
# 'timeavg' (time-weighted average) metric is used to calculate the mean
# number of failed servers over the entire simulation period.
*.repairCenter.failedServers.result-recording-modes = timeavg
