[General]
network = src.ServerSystem
sim-time-limit = 8760h # 1 год в часах
simtime-resolution = us

# Запускаем исследование для разного количества программистов (от 1 до 5)
*.repairCenter.numProgrammers = ${num=1..5}

# Устанавливаем среднее время атак для серверов
*.server[0].attackMean = 14h
*.server[1].attackMean = 26h
*.server[2].attackMean = 32h
*.server[3].attackMean = 64h
*.server[4].attackMean = 70h

# Настройка сбора статистики для вычисления среднего числа сломанных серверов
*.repairCenter.failedServers.result-recording-modes = timeavg
